services:
  db:
    image: postgres:16
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: library-app
    ports:
      - "8080:8080"
    depends_on:
      - db
